#pragma once

#include <cstdint>

#include "../Activity.h"

// "Apagón" — a Lights Out logic puzzle for e-ink.
// A grid of lights; pressing a cell toggles it and its 4 orthogonal neighbours.
// Goal: turn every light off. Pure deduction, no timing — ideal for slow e-ink
// refresh and a D-pad + Confirm layout.
//
// Controls: D-pad moves the cursor, Confirm presses the cell under it,
// Back exits. When solved, Confirm advances to the next (harder) level.
//
// Puzzles are generated by scrambling an all-off board with random presses,
// which guarantees a solution always exists.
class ApagonActivity final : public Activity {
  static constexpr int GRID = 5;

  bool lights[GRID][GRID];  // true = light on
  int cursorX = GRID / 2;
  int cursorY = GRID / 2;
  uint32_t moves = 0;
  uint32_t level = 1;
  bool solved = false;

  // Toggle (x,y) and its orthogonal neighbours (the Lights Out rule).
  void press(int x, int y);
  // Build a solvable board for the current level.
  void newPuzzle();
  // True when every light is off.
  bool isAllOff() const;
  // On a solve, record a new best (fewest moves) and persist it.
  void recordBestIfSolved();

 public:
  explicit ApagonActivity(GfxRenderer& renderer, MappedInputManager& mappedInput)
      : Activity("Apagon", renderer, mappedInput) {}

  void onEnter() override;
  void loop() override;
  void render(RenderLock&&) override;
};
