// Generates PoliticalSimData.h from the political-simulator Spain data.
// Loads the country + card JS (which push onto window.GAME_COUNTRIES.es),
// strips emoji, and emits C++ const tables that live in flash (.rodata).
import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';

const SRC = '/Users/alejandro/Projects/political-simulator/js/countries/spain';
const OUT = '/Users/alejandro/Projects/crosspet/src/activities/tools/PoliticalSimData.h';

// Order: country first (defines the object + intro), then all card files.
const cardFiles = [
  'escandalos', 'tribunales', 'socios', 'medios', 'economia', 'moncloa',
  'internacional', 'partido', 'crisis', 'coyuntura', 'oposicion', 'torrente',
];

const sandbox = { window: {} };
vm.createContext(sandbox);
function load(file) {
  const code = fs.readFileSync(file, 'utf8');
  vm.runInContext(code, sandbox, { filename: file });
}
load(path.join(SRC, 'country.js'));
for (const f of cardFiles) load(path.join(SRC, 'cards', f + '.js'));

const C = sandbox.window.GAME_COUNTRIES.es;

// ---- emoji / non-renderable stripping ----------------------------------
// Keep Latin + Spanish punctuation (accents, ¿¡ « » — … © ®). Drop emoji,
// regional indicators (flags), dingbats, variation selectors, ZWJ.
function strip(s) {
  if (s == null) return '';
  let out = '';
  for (const ch of String(s)) {
    const cp = ch.codePointAt(0);
    if (cp === 0xFE0F || cp === 0xFE0E || cp === 0x200D) continue; // VS / ZWJ
    if (cp >= 0x1F000) continue;                    // emoji planes
    if (cp >= 0x2600 && cp <= 0x27BF) continue;      // misc symbols + dingbats
    if (cp >= 0x1F1E6 && cp <= 0x1F1FF) continue;    // regional indicators
    if (cp >= 0x2190 && cp <= 0x21FF) continue;      // arrows
    if (cp === 0x2B50 || cp === 0x2B55) continue;    // star / circle
    out += ch;
  }
  // collapse whitespace left by stripped icons
  return out.replace(/\s+/g, ' ').trim();
}

// ---- C++ string literal (UTF-8, escape backslash + quote) ---------------
function cstr(s) {
  const v = strip(s).replace(/\\/g, '\\\\').replace(/"/g, '\\"');
  return '"' + v + '"';
}

const STATS = ['pueblo', 'jueces', 'socios', 'partido'];
const statIdx = (id) => STATS.indexOf(id);

const out = [];
const p = (l = '') => out.push(l);

p('// AUTO-GENERATED by scripts/gen_polsim.mjs — do not edit by hand.');
p('// Source: political-simulator Spain edition (Reigns-style card game).');
p('// All strings live in flash (.rodata); nothing here is copied to RAM.');
p('#pragma once');
p('#include <cstdint>');
p('#include "PoliticalSimTypes.h"');
p('');
p('namespace polsim {');
p('');

// flag string-array helpers: emit a static null-terminated const char* array
let flagArrCount = 0;
const flagArr = (arr) => {
  if (!arr || !arr.length) return 'nullptr';
  const name = `kFlags${flagArrCount++}`;
  p(`static const char* const ${name}[] = {${arr.map(cstr).join(', ')}, nullptr};`);
  return name;
};
let condArrCount = 0;
const condArr = (arr) => {
  if (!arr || !arr.length) return { name: 'nullptr', count: 0 };
  const name = `kCond${condArrCount++}`;
  const items = arr.map(([stat, op, val]) => `{${statIdx(stat)}, '${op}', ${val}}`);
  p(`static const Cond ${name}[] = {${items.join(', ')}};`);
  return { name, count: arr.length };
};

function eff(e) {
  e = e || {};
  return `{${e.pueblo | 0}, ${e.jueces | 0}, ${e.socios | 0}, ${e.partido | 0}}`;
}
function optLiteral(o) {
  o = o || {};
  const setName = flagArr(o.set);
  const quip = o.quip ? cstr(o.quip) : 'nullptr';
  return `{${cstr(o.label)}, ${eff(o.effects)}, ${setName}, ${quip}}`;
}

// We must emit the flag/cond arrays BEFORE the card that references them,
// so build each card's literal while emitting its dependencies inline.
p('// ---- cards ----');
const cardLiterals = [];
for (const card of C.cards) {
  const reqName = flagArr(card.requires);
  const excName = flagArr(card.excludes);
  const cond = condArr(card.ifStat);
  const left = optLiteral(card.left);
  const right = optLiteral(card.right);
  cardLiterals.push(
    `  {${cstr(card.id)}, ${cstr(card.tag)}, ${cstr(card.char)}, ${cstr(card.role)}, ` +
    `${cstr(card.text)}, ${card.minDay | 0}, ${reqName}, ${excName}, ${cond.name}, ${cond.count}, ` +
    // weights scaled ×10 so fractional relative probabilities (0.4–0.8)
    // survive as integers (default weight 1 → 10).
    `${card.urgent ? 'true' : 'false'}, ${card.repeat ? 'true' : 'false'}, ${Math.round((card.weight ?? 1) * 10)}, ` +
    `${left}, ${right}}`
  );
}
p(`static const Card kCards[] = {`);
p(cardLiterals.join(',\n'));
p('};');
p(`static const int kCardCount = ${C.cards.length};`);
p('');

// ---- intro card ----
{
  const card = C.intro;
  const left = optLiteral(card.left);
  const right = optLiteral(card.right);
  p('// ---- intro (jura del cargo) ----');
  p(`static const Card kIntro = {${cstr(card.id)}, ${cstr(card.tag)}, ${cstr(card.char)}, ${cstr(card.role)}, ` +
    `${cstr(card.text)}, 0, nullptr, nullptr, nullptr, 0, false, false, 1, ${left}, ${right}};`);
  p('');
}

// ---- stat endings: [stat][0=low,1=high] ----
p('// ---- stat endings (una stat toca 0 o 100) ----');
p('static const Ending kStatEndings[4][2] = {');
for (const s of STATS) {
  const e = C.endings[s];
  const cell = (d) => `{${cstr(e[d].stamp)}, ${cstr(e[d].headline)}, ${cstr(e[d].body)}, ${cstr(e[d].epitaph)}}`;
  p(`  {${cell('low')}, ${cell('high')}},`);
}
p('};');
p('');

// ---- secret endings ----
p('// ---- secret endings ----');
const secretLiterals = [];
for (const se of C.secretEndings) {
  const reqName = flagArr(se.requires);
  const excName = flagArr(se.excludes);
  const cond = condArr(se.ifStat);
  const lo = se.allStatsBetween ? se.allStatsBetween[0] : -1;
  const hi = se.allStatsBetween ? se.allStatsBetween[1] : -1;
  secretLiterals.push(
    `  {${cstr(se.id)}, ${reqName}, ${excName}, ${cond.name}, ${cond.count}, ` +
    `${se.minDay | 0}, ${se.maxDay | 0}, ${lo}, ${hi}, ` +
    `{${cstr(se.stamp)}, ${cstr(se.headline)}, ${cstr(se.body)}, ${cstr(se.epitaph)}}}`
  );
}
p('static const SecretEnding kSecretEndings[] = {');
p(secretLiterals.join(',\n'));
p('};');
p(`static const int kSecretCount = ${C.secretEndings.length};`);
p('');

// ---- stat labels ----
p('static const char* const kStatLabels[4] = {' +
  STATS.map((s) => cstr(C.stats.find((x) => x.id === s).label)).join(', ') + '};');
p(`static const char* const kLeader = ${cstr(C.leader)};`);
p(`static const char* const kPalace = ${cstr(C.palace)};`);
p('');
p('}  // namespace polsim');
p('');

fs.writeFileSync(OUT, out.join('\n'));
console.error(`Wrote ${OUT}`);
console.error(`cards=${C.cards.length} secrets=${C.secretEndings.length} flagArrs=${flagArrCount} condArrs=${condArrCount}`);
